### PR TITLE
Check if filename is a URL before checking if file exists

### PR DESCRIPTION
**Pull request by willprice**
> Check if filename is a URL before checking if file exists.
> 
> It does so by parsing the filename and checking if it's a URL with a scheme (the "http" or "rstp" in "http://youtube.com/..." or in "rstp://192.168.1.15:5544/") before parsing if a file exists. So, if the path is a file, it will still do the check.
> 
> This should solve #35.
> 
> I needed it so I added it (and I tested it, I'm already using this fix).

Continuation of @tiangolo's work in #47

### CODE REVIEW

**Comment by willprice** [comment]
Thanks @tiangolo for your work 👍

**Comment by willprice** [comment]
Just going to run the smoke tests locally then I'll merge in.

**Comment by tiangolo** [comment]
Great! Thanks!

**Comment by tiangolo** [comment]
Great! Thanks! 🎉

**Comment by willprice** [comment]
Sorry it took me a while, I've been very busy recently.

Would you mind pulling it down and running the smoke tests? It'd be nice to have someone else to validate it, especially since I released it on PyPi too!

**Pull request merged**
