### PR TITLE
Fix DBusException issue #5

### PR DESCRIPTION
**Pull request by jthuraisamy**
https://github.com/willprice/python-omxplayer-wrapper/issues/5

### CODE REVIEW

**Comment by willprice** [comment]
Have you had any issues where you try and play files consecutively? e..g
```python
OMXPlayer('file1').play()
# wait
OMXPlayer('file2').play()
```

**Comment by jthuraisamy** [comment]
I haven't tried it in that exact manner yet, though I have tried playing two streams a while ago and it resulted in both of them playing at the same time flickering rapidly between streams. Have you experienced similar?

**Comment by JonnyAlpha** [comment]
Will, I am trying to play two streams consecutively without a gap or have two players open pause one play the other and un pause the first, is this possible?

**Comment by willprice** [comment]
Hi JonnyAlpha, I'm continuing this conversation in #7

**Comment by willprice** [comment]
@jthuraisamy, check out issues #3

**Pull request merged**
